// import { useState, useEffect } from "react";

// const Disclaimer = () => {
//   const [isVisible, setIsVisible] = useState(false);

//   useEffect(() => {
//     const hasDismissed = localStorage.getItem("ai_disclaimer_dismissed");
//     if (!hasDismissed) {
//       setIsVisible(true);
//     }
//   }, []);

//   const handleDismiss = () => {
//     localStorage.setItem("ai_disclaimer_dismissed", "true");
//     setIsVisible(false);
//   };

//   if (!isVisible) return null;

//   return (
//     <div className="fixed bottom-2 left-1/2 transform -translate-x-1/2 bg-gray-800 text-white text-xs p-2 px-4 rounded-md flex items-center justify-between max-w-md shadow-lg">
//       <span className="mr-3">
//         The output generated by our <strong>Agentic AI</strong> may not always be accurate.
//       </span>
//       <button
//         onClick={handleDismiss}
//         className="text-gray-300 hover:text-white text-xs"
//       >
//         ✕
//       </button>
//     </div>
//   );
// };

// export default Disclaimer;


// import { useState, useEffect } from "react";

// const Disclaimer = () => {
//   const [isVisible, setIsVisible] = useState(false);

//   useEffect(() => {
//     const hasDismissed = sessionStorage.getItem("ai_disclaimer_dismissed");
//     if (!hasDismissed) {
//       setIsVisible(true);
//     }
//   }, []);

//   const handleDismiss = () => {
//     sessionStorage.setItem("ai_disclaimer_dismissed", "true");
//     setIsVisible(false);
//   };

//   if (!isVisible) return null;

//   return (
//     <div className="fixed bottom-0 left-0 w-full bg-gray-900 text-white text-xs p-2 text-center flex items-center justify-center shadow-lg animate-fade-in">
//       <span className="mr-3">
//         The output generated by our <strong>Agentic AI</strong> may not always be accurate.
//       </span>
//       <button
//         onClick={handleDismiss}
//         className="ml-3 px-2 py-1 text-gray-300 hover:text-white text-xs bg-gray-700/50 hover:bg-gray-600 rounded transition"
//       >
//         ✕
//       </button>
//     </div>
//   );
// };

// export default Disclaimer;

import { useState } from "react";

const Disclaimer = () => {
  const [isVisible, setIsVisible] = useState(true);

  return (
    <div className="fixed bottom-0 w-full bg-gray-900 text-white text-xs p-2 text-center flex items-center justify-center shadow-lg z-10">
      <span className="mr-3">
        The output generated by our <strong>Agentic AI</strong> may not always be accurate.
      </span>
    </div>
  );
};

export default Disclaimer;
